kind: pipeline
type: kubernetes
name: docker

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: git.anshulg.com/ansg191/traefik-dns-rs
      registry: git.anshulg.com
      auto_tag: "true"
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
