[advisories]
vulnerability = "deny"
unmaintained = "deny"
yanked = "deny"

ignore = [
    "RUSTSEC-2020-0071"
]

[licenses]
copyleft = "deny"
allow-osi-fsf-free = "either"

allow = [
    "MPL-2.0"
]

[[licenses.clarify]]
name = "ring"
version = "*"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 }
]

[bans]
skip = [
    { name = "syn", version = "=1.0.109" }
    #{ name = "ansi_term", version = "=0.11.0" },
]
skip-tree = [
    #{ name = "ansi_term", version = "=0.11.0", depth = 20 },
]
